### ISSUE TITLE
Inferring return types of Object?

### ISSUE THREAD

**Issue by newobj** [ccontrols/structured-types#3]
Hi there,

I'm using what I believe to be a standard setup, with the example code provided.

This is my input file:

```
export class MyClass {}
export class Test {
  make() { return new MyClass() }
}
```

structured-types emits this as:

```
{
  MyClass: { name: 'MyClass', kind: 13, properties: [] },
  Test: {
    name: 'Test',
    kind: 13,
    properties: [ { name: 'make', kind: 11 } ]
  }
}
```

Notably, 'make' does not have a return type emitted. It seems to be able to deduce things like numbers etc, but once I get into Object-like (even Object itself) return types, it no longer emits any return type.

Am I doing something wrong? Is this a fundamental limitation? Thanks!

**Comment by atanasster** [comment]
Hi @newobj, thanks for the feedback - I dont think it can report such return types, but will check with the typescript compiler guys if they have any hints.

Can you not annotate the code with jsdoc or typescript types?

Also - have you cheked the site where you can test out some code examples: https://bit.ly/3AAn9Pp

Yo can also add other type systems like typedoc or jsdoc for comparison - and they are mostly not inferring return types at all.

**Comment by newobj** [comment]
Thanks @atanasster. I "can" annotate the code, but my use case is to have people type "valid" (and preferably minimal) TS code, and extract that to a metadata system elsewhere. I'm a little surprised it can't at least infer Object/Class (the inference works for "number", for example) - though I certainly didn't have many expectations about it being able to tell me the name of the class.

**Comment by atanasster** [comment]
@newobj - actually there was way using the symbol and it should be fixed - can you please try again at the playground: https://bit.ly/3AAn9Pp

I will also release the packages soon

**Comment by newobj** [comment]
That's amazing! Wow! Thank you! 🥇

**Comment by atanasster** [comment]
should be released now under `3.20.1`

You are welcome, I appreciate you giving it a try. 

The library should be a version 0.6/0.7 but I made a mistake copying the lerna files and its a 3.x now. 
So I really need as much feedback as possible and since there are still not many users am vastly available for fixes/enhancements :)

**Comment by newobj** [comment]
My pleasure. I have a few more issues I will open in a bit. Thanks again.

**Comment by atanasster** [comment]
Thanks a lot
